[package]
name = "violet"
version = "0.1.0"
edition = "2024"
authors = ["mikkurogue"]

[dependencies]
anyhow = "1.0.97"
crossterm = "0.28.1"
tree-sitter = "0.20.10"
tree-sitter-rust = "0.20.4"

[build-dependencies]
cc="*"
